name: marlin_auto_build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - "builds/**"
  schedule:
    - cron: "0 10 * * 0"

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: oskardotglobal/marlin_auto_build@master
